name: hydrodataset
channels:
  - conda-forge
  - defaults
dependencies:
  # dev tools
  - python=3.10
  - pip
  - bump2version
  - wheel
  - watchdog
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - black
  - flake8
  - tqdm

  - pytest
  - pytest-runner

  # data tools
  - pandas
  - xarray
  - netcdf4
  - scipy
  - pint
  - pint-pandas
  - pint-xarray

  # request tools
  - async-retriever

  - pip
  - pip:
    - timezonefinder[numba]
    - hydroutils
