name: hydrodataset
channels:
  - conda-forge
  - defaults
dependencies:
  # dev tools
  - python=3.10
  - bump2version
  - wheel
  - watchdog
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - black
  - flake8

  - pytest
  - pytest-runner

  # data tools
  - xarray
  - netcdf4
  - zarr
  - dask
  - distributed
  - bokeh>=2.4.2
  - scipy
  - pint
  - pint-pandas
  - pint-xarray

  - pip
  - pip:
    - timezonefinder[numba]
    - codetiming
    - hydroutils
