name: hydro-bench
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - pygeoogc
  - pygeoutils
  - py3dep
  - pynhd
  - pygeohydro
  - pydaymet
  - geemap
  - xarray=0.17
  - tqdm
  - sphinx
