name: hydrodataset
channels:
  - conda-forge
  - defaults
dependencies:
  # dev tools 
  - pip
  - bump2version
  - wheel
  - watchdog
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - black
  - tqdm

  - pytest
  - pytest-runner

  # data tools
  - pandas
  - xarray
  - scipy
  - pint
  - pint-pandas
  - pint-xarray

  # request tools
  - async-retriever

  - pip
  - pip:
    - hydroutils
