# This workflows will upload a Python Package using uv and twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: pypi

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # Fetch all history for all tags and branches
                  ref: ${{ github.ref }}  # Checkout the exact tag/ref that triggered this workflow

            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                  enable-cache: true
                  cache-dependency-glob: "**/pyproject.toml"

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: uv sync --extra release

            # Temporarily skip tests until they are fully implemented
            # Tests require large dataset downloads not suitable for CI
            # - name: Run tests
            #   run: uv run pytest tests/ -v

            - name: Verify git tag and version
              run: |
                  echo "Current ref: ${{ github.ref }}"
                  echo "Current ref name: ${{ github.ref_name }}"
                  git describe --tags --exact-match || echo "Not on exact tag"
                  git log -1 --oneline
                  git tag -l

            - name: Build package
              run: uv run python -m build

            - name: Verify package version (no local segment)
              run: |
                  # Check if version contains '+' (local version identifier)
                  WHEEL_FILE=$(ls dist/*.whl | head -1)
                  echo "Built wheel: $WHEEL_FILE"
                  if echo "$WHEEL_FILE" | grep -q '+'; then
                      echo "Error: Package version contains local segment ('+'), which PyPI does not accept"
                      exit 1
                  fi
                  echo "✓ Package version is PyPI-compliant"

            - name: Check package with twine
              run: uv run twine check dist/*

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: uv run twine upload dist/*
